# Generated by Django 5.2.3 on 2025-06-26 10:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript')], default='cpp', max_length=20)),
                ('source_code', models.TextField(help_text='The source code to be executed')),
                ('input_data', models.TextField(blank=True, help_text='Input data for the program')),
                ('output', models.TextField(blank=True, help_text='Program output')),
                ('error_output', models.TextField(blank=True, help_text='Error messages')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in KB', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Code Execution',
                'verbose_name_plural': 'Code Executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
